### ISSUE TITLE
Using Raspberry Pi 4 - Installer Fails at starting minikube

### ISSUE THREAD

**Issue by Nodering** [dragonchain/dragonchain-installer#4]
Hello,

I performed a clean install on Raspberry Pi 4, Unbuntu 20.04, installed latest updates and the installer fails with the below notes after entering in node details:

> What level chain would you like to create? [1-5]: 2
> What name would you like for this chain? <entered my node name>
> Input the Chain ID for this chain (from Dragonchain console for Dragonnet support, otherwise leave empty): <entered my chain id>
> Input the matchmaking token for this chain (from Dragonchain console for Dragonnet support, otherwise leave empty): <entered my matchmaking token>
> What port would you like to run the dragonchain on? [30000-32767]: 30000
> What endpoint would you like to broadcast that this chain is available at? (i.e. http://my.domain) (Leave blank to find your public ip and use that): 
> Defaulting to endpoint with public ip <my ip address>
> 
> Starting minikube cluster; This can take a while
> * minikube 1.12.1 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v1.12.1
> * To disable this notice, run: 'minikube config set WantUpdateNotification false'
> 
> ! minikube v1.7.2 on Ubuntu 20.04 (arm64)
>   - MINIKUBE_IN_STYLE=false
> * Using the none driver based on user configuration
> * Running on localhost (CPUs=4, Memory=3793MB, Disk=14638MB) ...
> * 
> X Unable to start VM. Please investigate and run 'minikube delete' if possible: create: precreate: exec: "docker": executable file not found in $PATH
> * 
> * minikube is exiting due to an error. If the above message is not useful, open an issue:
>   - https://github.com/kubernetes/minikube/issues/new/choose
> Failed to start minikube. Resolve errors to continue:
> exit status 70

**Comment by cheeseandcereal** [comment]
In order to run with the 'none' driver, which is required on the raspi, you must install docker yourself before running the dragonchain installer. There is no great 'generic' way to install/ensure docker is running, so it was excluded as an automated part of this installer.

**Comment by Nodering** [comment]
Thank you for the clarification! I will continue tinkering :)
